inputs: final: prev:

let
  pkgs = final;

  locales = {
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LOCALE_ARCHIVE =
      if pkgs.system == "x86_64-linux"
      then "${pkgs.glibcLocales}/lib/locale/locale-archive"
      else "";
  };

  customAgda = inputs.agda-nixpkgs.legacyPackages.${pkgs.system};

  agdaStdlib = customAgda.agdaPackages.standard-library;

  agdaStdlibClasses = customAgda.agdaPackages.mkDerivation {
    inherit (locales) LANG LC_ALL LOCALE_ARCHIVE;
    pname = "agda-stdlib-classes";
    version = "2.1.1";
    src = pkgs.fetchFromGitHub {
      owner = "agda";
      repo = "agda-stdlib-classes";
      rev = "73f4da05aeea040fea4587629f9fd83a8f04e656";
      hash = "sha256-Uj3bmgMtdBJYGW7K+0rqxexm6M47odBuWyRo0aoYmZg=";
    };
    meta = { };
    libraryFile = "agda-stdlib-classes.agda-lib";
    everythingFile = "standard-library-classes.agda";
    buildInputs = [ agdaStdlib ];
  };

  agdaStdlibMeta = customAgda.agdaPackages.mkDerivation {
    inherit (locales) LANG LC_ALL LOCALE_ARCHIVE;
    pname = "agda-stdlib-meta";
    version = "2.1.1";
    src = pkgs.fetchFromGitHub {
      owner = "agda";
      repo = "agda-stdlib-meta";
      rev = "v2.1.1";
      hash = "sha256-qOoThYMG0dzjKvwmzzVZmGcerfb++MApbaGRzLEq3/4=";
    };
    meta = { };
    libraryFile = "agda-stdlib-meta.agda-lib";
    everythingFile = "Main.agda";
    buildInputs = [ agdaStdlib agdaStdlibClasses ];
  };

  deps = [ agdaStdlib agdaStdlibClasses agdaStdlibMeta ];
  agdaWithPkgs = p: customAgda.agda.withPackages { pkgs = p; };

  attrs = pkgs.recurseIntoAttrs rec {
    agda = agdaWithPkgs deps;

    latex = pkgs.texlive.combine {
      inherit (pkgs.texlive)
        scheme-small
        xits
        collection-latexextra
        collection-latexrecommended
        collection-mathscience
        bclogo
        latexmk;
    };

    docs = pkgs.stdenv.mkDerivation {
      inherit (locales) LANG LC_ALL LOCALE_ARCHIVE;
      pname = "docs";
      version = "0.1";
      src = ../docs/agda-spec;
      meta = { };
      buildInputs = [ agda latex pkgs.python3 ];
      buildPhase = ''
        OUT_DIR=$out make docs
      '';
      doCheck = true;
      checkPhase = ''
        test -n "$(find $out/pdfs/ -type f -name '*.pdf')"
      '';
      dontInstall = true;
    };

    # this derivation generates the Haskell code from the Agda spec, but does
    # not build or test it.
    # TODO(georgy.lukyanov): share agda typechecking with the docs derivation
    hsSrc = pkgs.stdenv.mkDerivation {
      inherit (locales) LANG LC_ALL LOCALE_ARCHIVE;
      pname = "agda-spec-hs-src";
      version = "0.1";
      src = ../docs/agda-spec;
      meta = { };
      buildInputs = [ agda customAgda.ghc customAgda.cabal-install ];
      buildPhase = ''
        OUT_DIR=$out make hs
      '';
      doCheck = true;
      checkPhase = ''
        test -n "$(find $out/haskell/ -type f -name '*.hs')"
      '';
      dontInstall = true;
    };

    # this derivation picks up the Haskell project generated by hsSrc and
    # builds and tests it. Note that the profiled build is intentionally disabled
    # as is causes some GHC versions to panic.
    hsExe = customAgda.haskell.lib.disableLibraryProfiling (customAgda.haskellPackages.callCabal2nixWithOptions "cardano-consensus-executable-spec" "${hsSrc}/haskell/Spec" "--no-haddock" { });

    shell = pkgs.mkShell {
      packages = [
        agda
        latex
        customAgda.ghc
        customAgda.cabal-install
        final.pkg-config
        final.libsodium-vrf
        final.blst
        final.secp256k1
        final.zlib
      ];
    };
  };
in
{ agda-spec = attrs; }
