#! /bin/bash
rm -f tmp/my.db tmp/up.db tmp/my.lfst tmp/demo tmp/reqs
set -eux
cabal build exe:leiosdemo202510
ln -s $(cabal list-bin exe:leiosdemo202510) tmp/demo
tmp/demo generate tmp/up.db tmp/my.lfst tmp/myManifest.json
cp tmp/{up,my}.db
sqlite3 tmp/my.db "SELECT ebSlot, PRINTF('%X', ebId), ebId FROM ebPoints ORDER BY ebId ASC" # dump points
sqlite3 tmp/my.db 'SELECT ebId, MAX(txOffset) FROM ebTxs GROUP BY ebId' # dump sizes
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
sqlite3 tmp/my.db 'UPDATE ebTxs SET txBytes = NULL WHERE ebId = -9223372036843241473'
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
tmp/demo MsgLeiosBlockTxsOffer tmp/my.lfst Alice -9223372036848484353 -9223372036843241473
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
tmp/demo MsgLeiosBlockTxsOffer tmp/my.lfst Bob -9223372036848484353 -9223372036843241473
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
sqlite3 tmp/my.db 'UPDATE ebTxs SET txBytes = NULL WHERE ebId = -9223372036848484353'
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
tmp/demo fetch-logic-iteration tmp/my.db tmp/my.lfst | tee -a tmp/reqs
jq . tmp/my.lfst
sqlite3 tmp/my.db 'SELECT ebId FROM ebTxs WHERE txBytes IS NULL GROUP BY ebId' # dump incompletes
set +x
cat tmp/reqs | grep -e MSG | grep -e Alice | cut -d' ' -f3- | while IFS= read -r line; do
    set -x
    tmp/demo MsgLeiosBlockTxsRequest tmp/up.db $line | xxd -plain -revert >tmp/foo.bin
    tmp/demo MsgLeiosBlockTxs tmp/my.db tmp/my.lfst Alice tmp/foo.bin
    set +x
    jq . tmp/my.lfst
    sqlite3 tmp/my.db 'SELECT ebId FROM ebTxs WHERE txBytes IS NULL GROUP BY ebId' # dump incompletes
done
cat tmp/reqs | grep -e MSG | grep -e Bob | cut -d' ' -f3- | while IFS= read -r line; do
    set -x
    tmp/demo MsgLeiosBlockTxsRequest tmp/up.db $line | xxd -plain -revert >tmp/foo.bin
    tmp/demo MsgLeiosBlockTxs tmp/my.db tmp/my.lfst Bob tmp/foo.bin
    jq . tmp/my.lfst
    sqlite3 tmp/my.db 'SELECT ebId FROM ebTxs WHERE txBytes IS NULL GROUP BY ebId' # dump incompletes
    set +x
done
