header
 = base.ns8<byronHeader,
            serialisedShelleyHeader<shelley.header>,
            serialisedShelleyHeader<allegra.header>,
            serialisedShelleyHeader<mary.header>,
            serialisedShelleyHeader<alonzo.header>,
            serialisedShelleyHeader<babbage.header>,
            serialisedShelleyHeader<conway.header>,
            serialisedShelleyHeader<dijkstra.header>>

byronHeader = [byronRegularIdx, #6.24(bytes .cbor byron.blockhead)]
            / [byronBoundaryIdx, #6.24(bytes .cbor byron.ebbhead)]

byronBoundaryIdx = [0, base.word32]
byronRegularIdx = [1, base.word32]

serialisedShelleyHeader<era> = #6.24(bytes .cbor era)

;# include byron as byron
;# include shelley as shelley
;# include allegra as allegra
;# include mary as mary
;# include alonzo as alonzo
;# include babbage as babbage
;# include conway as conway
;# include dijkstra as dijkstra
;# import base as base
