ledgerState =
  telescope7<byron.ledgerstate,
             versionedShelleyLedgerState<shelley.ledgerstate>,
             versionedShelleyLedgerState<allegra.ledgerstate>,
             versionedShelleyLedgerState<mary.ledgerstate>,
             versionedShelleyLedgerState<alonzo.ledgerstate>,
             versionedShelleyLedgerState<babbage.ledgerstate>,
             versionedShelleyLedgerState<conway.ledgerstate>>

versionedShelleyLedgerState<era> = [ shelleyVersion2, shelleyLedgerState<era> ]

shelleyVersion2 = 2

shelleyLedgerState<era> = [ withOrigin<shelleyTip>, era, shelleyTransition ]

shelleyTip = [slotno, blockno, hash]

shelleyTransition = word32

; TODO these should be imports from the ledger however they do not
; provide these definitions yet.
byron.ledgerstate = any
shelley.ledgerstate = any
allegra.ledgerstate = any
mary.ledgerstate = any
alonzo.ledgerstate = any
babbage.ledgerstate = any
conway.ledgerstate = any

;# import base
