headerState =
  [withOrigin<headerStateTip>, headerStateChainDep]

headerStateTip =
  ns8<byronAnnTip, annTip, annTip, annTip, annTip, annTip, annTip, annTip>

byronAnnTip = [slotno,
               hash,
               blockno,
               bool]

annTip = [slotno,
          hash,
          blockno]

headerStateChainDep =
  telescope8<pbftState,
             tpraosState,
             tpraosState,
             tpraosState,
             tpraosState,
             praosState,
             praosState,
             leiosState>

pbftState = {* keyhash => [* slotno]}

tpraosState = [withOrigin<slotno>, sl.chainDepState]

praosState = [withOrigin<slotno>,
              {* keyhash => word64},
              nonce,
              nonce,
              nonce,
              nonce,
              nonce,
              nonce]

leiosState = [praosState, maybe<announcedBy>]

announcedBy = [keyhash, ebReferencesAnnouncement]

;; These should belong to the Ledger
ebReferencesAnnouncement = [hash, word32]

sl.chainDepState = [prtclState, ticknState, nonce]

prtclState = [{* keyhash => word64}, nonce, nonce]

ticknState = [nonce, nonce]

;# import withOrigin, ns8, telescope8, slotno, hash, blockno, keyhash, word32, word64, nonce, maybe from base
