ledgerState =
  telescope8<byronLedgerState,
             shelleyLedgerState<shelley.ledgerstate>,
             shelleyLedgerState<allegra.ledgerstate>,
             shelleyLedgerState<mary.ledgerstate>,
             shelleyLedgerState<alonzo.ledgerstate>,
             shelleyLedgerState<babbage.ledgerstate>,
             shelleyLedgerState<conway.ledgerstate>,
             shelleyLedgerState<dijkstra.ledgerstate>>

byronLedgerState = [byronTip, byron.ledgerstate, byronTransition]

byronTip = withOrigin<blockno>

byronTransition = 0 .size 1 / [ * [pvMajor, pvMinor, pvAlt, blockno] ]

pvMajor = uint .size 2
pvMinor = uint .size 2
pvAlt = uint .size 1

shelleyLedgerState<eraSt> = [withOrigin<shelleyTip>,
                             eraSt,
                             shelleyTransition]

shelleyTip = [slotno, blockno, hash]

shelleyTransition = word32

; TODO these should be imports from the ledger however they do not
; provide these definitions yet.
byron.ledgerstate = any
shelley.ledgerstate = any
allegra.ledgerstate = any
mary.ledgerstate = any
alonzo.ledgerstate = any
babbage.ledgerstate = any
conway.ledgerstate = any
dijkstra.ledgerstate = any

;# import telescope8, withOrigin, slotno, blockno, hash, word32 from base
