versionedPraosState = [praosVersion, praosState]

praosVersion = 0

praosState = [withOrigin<slotno>,
              {* keyhash => word64},
              nonce,
              nonce,
              nonce,
              nonce,
              nonce]

;# import withOrigin, slotno, keyhash, word64, nonce from base
