ledgerStateSnapshot =
  [snapshotEncodingVersion2, extLedgerState]

snapshotEncodingVersion2 = 2

extLedgerState = [ledgerState, headerState, perasState]

;# import headerState from headerstate
;# import ledgerState from ledgerstate
;# import perasState from perasstate
