;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; This file is not yet finished!
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

toplevel = cardanoQuery / cardanoResult

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; Query
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

cardanoQuery = [0, cardanoBlockQuery]
             / [systemStartQuery]
             / [chainBlockNoQuery]
             / [chainPointQuery]

systemStartQuery = 1
chainBlockNoQuery = 2
chainPointQuery = 3

cardanoBlockQuery = queryIfCurrent
                  / queryAnyTime
                  / queryHardFork

queryAnyTime = [1, getEraStartQuery, eraIdx]

getEraStartQuery = [0]

queryHardFork = [2, getInterpreterQuery / getCurrentEraQuery]

getInterpreterQuery = [0]
getCurrentEraQuery = [1]

queryIfCurrent =
  [0, cardanoNs<byronQuery,
                shelleyQuery,
                shelleyQuery,
                shelleyQuery,
                shelleyQuery,
                shelleyQuery,
                shelleyQuery>
                ]

byronQuery = getUpdateInterfaceStateQuery

getUpdateInterfaceStateQuery = 0

shelleyQuery = getLedgerTipQuery
             / getEpochNoQuery
             / getNonMyopicMemberRewardsQuery
             / getCurrentPParamsQuery
             / getProposedPParamsUpdatesQuery
             / getStakeDistributionQuery
             / getUTxOByAddressQuery
             / getUTxOWholeQuery
             / debugEpochStateQuery
             / getCBORQuery
             / getFilteredDelegationsAndRewardAccountsQuery
             / getGenesisConfigQuery
             / debugNewEpochStateQuery
             / debugChainDepStateQuery
             / getRewardProvenanceQuery
             / getUTxOByTxInQuery
             / getStakePoolsQuery
             / getStakePoolParamsQuery
             / getRewardInfoPoolsQuery
             / getPoolStateQuery
             / getStakeSnapshotsQuery
             / getPoolDistrQuery
             / getStakeDelegDepositsQuery
             / getConstitutionQuery
             / getGovStateQuery
             / getDRepStateQuery
             / getDRepStakeDistrQuery
             / getCommitteeMembersStateQuery
             / getFilteredVoteDelegateesQuery
             / getAccountStateQuery
             / getSPOStakeDistrQuery
             / getProposalsQuery
             / getRatifyStateQuery
             / getFuturePParamsQuery
             / getBigLedgerPeerSnapshotQuery

getLedgerTipQuery = [0]
getEpochNoQuery = [1]
getNonMyopicMemberRewardsQuery = [2, set<either<coin, stakeCredential>>]
getCurrentPParamsQuery = [3]
getProposedPParamsUpdatesQuery = [4]
getStakeDistributionQuery = [5]
getUTxOByAddressQuery = [6, set<addr>]
getUTxOWholeQuery = [7]
debugEpochStateQuery = [8]
getCBORQuery = [9, shelleyQuery]
getFilteredDelegationsAndRewardAccountsQuery = [10, set<stakeCredential>]
getGenesisConfigQuery = [11]
debugNewEpochStateQuery = [12]
debugChainDepStateQuery = [13]
getRewardProvenanceQuery = [14]
getUTxOByTxInQuery = [15, set<txin>]
getStakePoolsQuery = [16]
getStakePoolParamsQuery = [17, set<keyhash>]
getRewardInfoPoolsQuery = [18]
getPoolStateQuery = [19, maybe<set<keyhash>>]
getStakeSnapshotsQuery = [20, maybe<set<keyhash>>]
getPoolDistrQuery = [21, maybe<set<keyhash>>]
getStakeDelegDepositsQuery = [22, set<stakeCredential>]
getConstitutionQuery = [23]
getGovStateQuery = [24]
getDRepStateQuery = [25, set<drepCredential>]
getDRepStakeDistrQuery = [26, set<drep>]
getCommitteeMembersStateQuery = [27, set<coldCredential>, set<hotCredential>, set<status>]
getFilteredVoteDelegateesQuery = [28, set<stakeCredential>]
getAccountStateQuery = [29]
getSPOStakeDistrQuery = [30, set<keyhash>]
getProposalsQuery = [31, set<govActionId>]
getRatifyStateQuery = [32]
getFuturePParamsQuery = [33]
getBigLedgerPeerSnapshotQuery = [34]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; Result
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

cardanoResult = cardanoBlockQueryResult
              / getSystemStartResult
              / getChainBlockNoResult
              / getChainPointResult

getSystemStartResult = time
getChainBlockNoResult = blockno
getChainPointResult = point

cardanoBlockQueryResult = queryAnytimeResult
                        / queryHardForkResult
                        / queryIfCurrentResult

queryAnytimeResult = getEraStartResult
getEraStartResult = maybe<bound>

queryHardForkResult = getInterpreterResult / getCurrentEraResult

getInterpreterResult = interpreter
interpreter = [* eraSummary]
eraSummary = [eraStart, eraEnd, eraParams]
eraStart = bound
eraEnd = null / bound
eraParams = [epochSize, slotLength, safeZone, genesisWindow]
epochSize = word64
slotLength = int  ; millisec
safeZone = standardSafeZone / unsafeIndefiniteSafeZone
standardSafeZone = [0, safeFromTip, safeBeforeEpoch]
safeFromTip = word64
safeBeforeEpoch = [0]
unsafeIndefiniteSafeZone = [1]
genesisWindows = word64

getCurrentEraResult = eraIdx

queryIfCurrentResult = byronResult
                     / shelleyResult

byronResult = getUpdateInterfaceStateResult

getUpdateInterfaceStateResult = upiState

shelleyResult = getLedgerTipResult
              / getEpochNoResult
              / getNonMyopicMemberRewardsResult
              / getCurrentPParamsResult
              / getProposedPParamsUpdatesResult
              / getStakeDistributionResult
              / getUTxOByAddressResult
              / getUTxOWholeResult
              / debugEpochStateResult
              / getCBORResult
              / getFilteredDelegationsAndRewardAccountsResult
              / getGenesisConfigResult
              / debugNewEpochStateResult
              / debugChainDepStateResult
              / getRewardProvenanceResult
              / getUTxOByTxInResult
              / getStakePoolsResult
              / getStakePoolParamsResult
              / getRewardInfoPoolsResult
              / getPoolStateResult
              / getStakeSnapshotsResult
              / getPoolDistrResult
              / getStakeDelegDepositsResult
              / getConstitutionResult
              / getGovStateResult
              / getDRepStateResult
              / getDRepStakeDistrResult
              / getCommitteeMembersStateResult
              / getFilteredVoteDelegateesResult
              / getAccountStateResult
              / getSPOStakeDistrResult
              / getProposalsResult
              / getRatifyStateResult
              / getFuturePParamsResult
              / getBigLedgerPeerSnapshotResult

getLedgerTipResult = point
getEpochNoResult = epochno
getNonMyopicMemberRewardsResult = nonMyopicRewards
getCurrentPParamsResult = pparams
getProposedPParamsUpdatesResult = proposedPPUpdates
getStakeDistributionResult = poolDistr
getUTxOByAddressResult = utxo
getUTxOWholeResult = utxo
debugEpochStateResult = epochState
getCBORResult = #6.24(bstr .cbor shelleyResult)
getFilteredDelegationsAndRewardAccountsResult = [delegations, rewardAccounts]
getGenesisConfigResult = compactGenesis
debugNewEpochStateResult = newEpochState
debugChainDepStateResult = chainDepState
getRewardProvenanceResult = rewardProvenance
getUTxOByTxInResult = utxo
getStakePoolsResult = set<keyhash>
getStakePoolParamsResult = map<keyhash, poolparams>
getRewardInfoPoolsResult = [rewardParams, map<keyhash, rewardInfoPool>]
getPoolStateResult = pstate
getStakeSnapshotsResult = stakeSnapshots
getPoolDistrResult = poolDistr
getStakeDelegDepositsResult = map<stakeCredential, coin>
getConstitutionResult = constitution
getGovStateResult = govState
getDRepStateResult = map<drepCredential, drepState>
getDRepStakeDistrResult = map<drep, coin>
getCommitteeMembersStateResult = committeeMembersState
getFilteredVoteDelegateesResult = voteDelegatees
getAccountStateResult = accountState
getSPOStakeDistrResult = map<keyhash, coin>
getProposalsResult = seq<govActionState>
getRatifyStateResult = ratifyState
getFuturePParamsResult = maybe<pparams>
getBigLedgerPeerSnapshotResult = ledgerPeerSnapshot

eraIdx = word8
word8 = 0..255
