cardanoTelescope<byron, shelley, allegra, mary, alonzo, babbage, conway>
  = [pastEra, pastEra, pastEra, pastEra, pastEra, pastEra, currentEra<conway>] /
    [pastEra, pastEra, pastEra, pastEra, pastEra, currentEra<babbage>] /
    [pastEra, pastEra, pastEra, pastEra, currentEra<alonzo>] /
    [pastEra, pastEra, pastEra, currentEra<mary>] /
    [pastEra, pastEra, currentEra<allegra>] /
    [pastEra, currentEra<shelley>] /
    [currentEra<byron>]

cardanoNs<byron, shelley, allegra, mary, alonzo, babbage, conway>
  = [6, conway] /
    [5, babbage] /
    [4, alonzo] /
    [3, mary] /
    [2, allegra] /
    [1, shelley] /
    [0, byron]

slotno = word64
blockno = word64
epochno = word64
relativeTime = int

hash = bstr
keyhash = bstr

withOriginTH<v> = [0]
                / [1, v]

withOrigin<v> = []
              / [v]

word32 = 0..4294967295
word64 = 0..18446744073709551615

nonce = [0]
      / [1, hash]

point = []
      / [ slotno, hash ]
