flowchart TD
    A(dpsNumIdsInFlight)
    B(dpsOutstandingFifo)
    C(dpsObjectsAvailableIds)
    D(dpsObjectsInflightIds)
    E(dpsObjectsPending)
    F(dpsObjectsOwtPool)

    G(dgsObjectsLiveMultiplicities)
    H(dgsObjectsInflightMultiplicities)
    I(dgsObjectsOwtPoolMultiplicities)

    EA{requestIds}
    EA-->|+count| A

    EB{handleReceiveIds}
    A -->|-count| EB
    EB -->|+ids| B
    IN1@{ shape: lin-cyl, label: "ids" } --o EB
    EB -->|+ids| C

    EC{requestObjects}
    C -->|-ids| EC
    EC -->|+ids| D
    EC --> |+count| G
    EC -->|+count| H

    ED{handleReceiveObjects}
    D -->|-ids| ED
    H -->|-count| ED
    IN2@{ shape: lin-cyl, label: "objects" } --o ED
    ED -->|objects| E

    EE{acknowledgeIds}
    B -->|-ids| EE
    
    EF{submitToPool}
    EE -.->|ids| EF
    E -->|-objects| EF
    EF -->|+objects| F
    EF -->|+count| I

    EG{Added to pool}
    F -->|-objects| EG
    G -->|-count| EG
    I -->|-count| EG

    EZ{makeDecision}

    EZ -.->|count| EA
    EZ -.->|ids| EC
    EZ -.->|ids| EE
