flowchart TD
    A(dpsNumIdsInFlight)
    B(dpsOutstandingFifo)
    C(dpsObjectsAvailableIds)
    D(dpsObjectsInflightIds)
    F(dpsObjectsOwtPool)

    H(dgsObjectsInflightMultiplicities)
    I(dgsObjectsOwtPoolMultiplicities)

    EA{onRequestIds}
    EA-->|+count| A
    B -->|-ids| EA
    C -->|-ids| EA

    EB{onReceiveIds}
    A -->|-count| EB
    EB -->|+ids| B
    IN1@{ shape: lin-cyl, label: "ids" } --o EB
    EB -->|+ids| C

    EC{onRequestObjects}
    C -->|-ids| EC
    EC -->|+ids| D
    EC -->|+count| H

    ED{onReceiveObjects / submitToPool}
    D -->|-ids| ED
    H -->|-count| ED
    IN2@{ shape: lin-cyl, label: "objects" } --o ED
    ED -->|+objects| F
    ED -->|+count| I

    EE{makeDecisions}
    EE -.->|readDecision : pdIdsToAck + pdIdsToReq + pdCanPipelineIdsReq/| EA
    EE -.->|readDecision : pdObjectsToReqIds| EC

    EG{Added to pool}
    F -->|-objects| EG
    I -->|-count| EG
