;
; LeiosNotify mini-protocol
;

leiosNotifyMessage
     = msgClientDone
     / msgLeiosNotificationRequestNext
     / msgLeiosBlockAnnouncement
     / msgLeiosBlockOffer
     / msgLeiosBlockTxsOffer

msgClientDone = [5] ; TODO: 5?
msgLeiosNotificationRequestNext = [1, 0]
msgLeiosBlockAnnouncement = [1, announcement]
msgLeiosBlockOffer = [2, point, size]
msgLeiosBlockTxsOffer = [3, point]

announcement = any ; TODO
size = uint .size 4
point = [slot, eb_hash]
eb_hash = bytes .size 32
slot = uint .size 8
