;
; LeiosFetch mini-protocol
;

leiosBlockFetchMessage
     = msgClientDone
     / msgLeiosBlockRequest
     / msgLeiosBlock
     / msgLeiosBlockTxsRequest
     / msgLeiosBlockTxs

msgClientDone   = [9] ; TODO: 9?
msgLeiosBlockRequest = [0, point]
msgLeiosBlock = [1, endorser_block]
msgLeiosBlockTxsRequest = [2, point, bitmaps]
msgLeiosBlockTxs = [3, point, bitmaps, txList] 

point = [slot, eb_hash]
endorser_block = any ; TODO
bitmaps = any ; TODO
txList = [ *tx ] ; REVIEW: how to specify length-definite list?

slot = uint .size 8
eb_hash = bytes .size 32
tx = any ; TODO: use conway.tx
