cardanoLedgerStateSnapshot =
  [snapshotEncodingVersion1, cardanoExtLedgerState]

snapshotEncodingVersion1 = 1

cardanoExtLedgerState = [cardanoLedgerState, cardanoHeaderState]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; Ledger state
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

cardanoLedgerState =
  cardanoTelescope<byron.ledgerstate,
                   versionedShelleyLedgerState<shelley.ledgerstate>,
                   versionedShelleyLedgerState<allegra.ledgerstate>,
                   versionedShelleyLedgerState<mary.ledgerstate>,
                   versionedShelleyLedgerState<alonzo.ledgerstate>,
                   versionedShelleyLedgerState<babbage.ledgerstate>,
                   versionedShelleyLedgerState<conway.ledgerstate>>

pastEra = [bound, bound]

currentEra<st> = [bound, st]

bound = [relativeTime, slotno, epochno]

versionedShelleyLedgerState<era> = [ shelleyVersion2, shelleyLedgerState<era> ]

shelleyVersion2 = 2

shelleyLedgerState<era> = [ withOrigin<shelleyTip>, era, shelleyTransition ]

shelleyTip = [slotno, blockno, hash]

shelleyTransition = word32

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; Header state
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

cardanoHeaderState =
  [withOrigin<cardanoHeaderStateTip>, cardanoHeaderStateChainDep]

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;
    ;; Ann tip
    ;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

cardanoHeaderStateTip =
  cardanoNs<byronAnnTip, annTip, annTip, annTip, annTip, annTip, annTip>

annTip = [slotno, hash, blockno]

byronAnnTip = [slotno, hash, blockno, bool]

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;
    ;; Chain dep state
    ;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

cardanoHeaderStateChainDep =
  cardanoTelescope<versionedPbftState,
                   versionedTPraosState,
                   versionedTPraosState,
                   versionedTPraosState,
                   versionedTPraosState,
                   versionedPraosState,
                   versionedPraosState>

        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        ;;
        ;; Pbft
        ;;
        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

versionedPbftState = [serializationFormat1, {* keyhash => [* slotno]}]

        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        ;;
        ;; TPraos
        ;;
        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

versionedTPraosState =
  [serializationFormat1, [withOriginTH<slotno>, tpraosState]]

tpraosState = [prtclState, ticknState, nonce]

prtclState = [{* keyhash => word64}, nonce, nonce]

ticknState = [nonce, nonce]

        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        ;;
        ;; Praos
        ;;
        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

versionedPraosState = [praosVersion, praosState]

praosVersion = 0

praosState = [withOrigin<slotno>,
              {* keyhash => word64},
              nonce,
              nonce,
              nonce,
              nonce,
              nonce]

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; Basics
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

serializationFormat1 = 1

;# import byron as byron
;# import shelley as shelley
;# import allegra as allegra
;# import mary as mary
;# import alonzo as alonzo
;# import babbage as babbage
;# import conway as conway
;# include base
