name: Haskell CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  merge_group:

jobs:
  check-cabal-files:
    runs-on: ubuntu-latest

    steps:
    - name: Install Haskell
      uses: input-output-hk/setup-haskell@v1
      id: setup-haskell
      with:
        cabal-version: "3.10.1.0"

    - uses: actions/checkout@v3

    - name: Cabal check
      run: ./scripts/ci/check-cabal-files.sh

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Currently Hydra/Cicero build with 9.2.7

        # Consider re-enabling documentation in the respective
        # cabal.project.local.* when bumping to a newer GHC.
        ghc: ["8.10.7"]
        os: [windows-latest]

    env:
      # Modify this value to "invalidate" the cabal cache.
      CABAL_CACHE_VERSION: "2023-04-27"

      # current ref from: 27.02.2022
      SECP256K1_REF: ac83be33d0956faf6b7f61a60ab524ef7d6a473a

      SECP_CACHE_VERSION: "2023-04-27"

    steps:

    - name: Install Haskell
      uses: input-output-hk/setup-haskell@v1
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "3.10.1.0"
        pacman-packages: >
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libsodium
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-sed
          base-devel
          autoconf-wrapper
          autoconf
          automake
          libtool
          make

    - name: "[OUTPUT] cache keys: version, weeknum"
      id: cache-keys
      shell: bash
      run: |
        echo "weeknum=$(/usr/bin/date -u "+%W")" >> $GITHUB_OUTPUT
        echo "CACHE_VERSION=20220919" >> $GITHUB_OUTPUT
        echo "DIST_CACHE_VERSION=20221122" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v3

    - name: Install secp256k1
      uses: input-output-hk/setup-secp256k1@v1
      with:
        git-ref: ${{ env.SECP256K1_REF }}
        cache-version: ${{ env.SECP_CACHE_VERSION }}

    - name: "Configure cabal.project.local"
      run: |
        cp .github/workflows/cabal.project.local.Windows cabal.project.local

    - name: Update PATH
      run: |
        $env:PATH=("C:\msys64\mingw64\bin;{0}" -f $env:PATH)
        echo "PATH=$env:PATH" >> $env:GITHUB_ENV

    - name: Update Hackage and CHaP
      run: cabal update

    - name: Record dependencies
      id: record-deps
      run: |
        cabal build all --dry-run
        cat dist-newstyle/cache/plan.json | jq -L .github/workflows/jq-install-plan | sort | uniq > dependencies.txt

    - uses: actions/cache@v3
      name: "Cache `cabal store`"
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cache-dependencies-${{ env.CABAL_CACHE_VERSION }}-${{ steps.cache-keys.outputs.CACHE_VERSION }}-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('dependencies.txt') }}
        restore-keys: cache-dependencies-${{ env.CABAL_CACHE_VERSION }}-${{ steps.cache-keys.outputs.CACHE_VERSION }}-${{ runner.os }}-${{ matrix.ghc }}

    - uses: actions/cache@v3
      name: "Cache `dist-newstyle`"
      with:
        path: |
          dist-newstyle
          !dist-newstyle/**/.git
        key: cache-dist-${{ env.CABAL_CACHE_VERSION }}-${{ steps.cache-keys.outputs.DIST_CACHE_VERSION }}-${{ runner.os }}-${{ matrix.ghc }}-${{ steps.cache-keys.outputs.weeknum }}
        restore-keys: cache-dist-${{ env.CABAL_CACHE_VERSION }}-${{ steps.cache-keys.outputs.DIST_CACHE_VERSION }}-${{ runner.os }}-${{ matrix.ghc }}

    - name: Build dependencies
      run: cabal build --only-dependencies all -j

    - name: Build projects [build]
      run: cabal build all -j

    - name: Create baseline-benchmark
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cabal new-run ouroboros-consensus:mempool-bench -- --timeout=60 --csv mempool-baseline.csv  +RTS -T

    - name: Archive baseline results
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: baseline-benchmark
        path: |
          *benchmarks.json
          *benchmarks.csv


    # Uncomment the following back in for debugging. Remember to launch a `pwsh` from
    # the tmux session to debug `pwsh` issues. And be reminded that the `/msys2` and
    # `/msys2/mingw64` paths are not in PATH by default for the workflow, but tmate
    # will put them in.
    # You may also want to run
    #
    #   $env:PATH=("C:\Program Files\PowerShell\7;{0}" -f $env:ORIGINAL_PATH)
    #
    # to restore the original path.  Do note that some test might need msys2
    # and will silently fail if msys2 is not in path. See the "Run tests" step.
    #
    # - name: Setup tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true
