# from https://docusaurus.io/docs/deployment#deploying-to-github-pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:

    name: Deploy to GitHub Pages

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./docs/website

    strategy:
       fail-fast: false
       matrix:
         ghc: ["9.2.7"]
         os: [ubuntu-latest]

    env:
       # current ref from: 27.02.2022
       SECP256K1_REF: ac83be33d0956faf6b7f61a60ab524ef7d6a473a

       SECP_CACHE_VERSION: "2023-04-27"

       LD_LIBRARY_PATH: '/usr/local/lib'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: './docs/website/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Haskell
        uses: input-output-hk/setup-haskell@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.10.1.0"

      - name: Install build environment
        run: |
          sudo apt-get update
          sudo apt-get -y install libsodium-dev

      - name: Install secp256k1
        uses: input-output-hk/setup-secp256k1@v1
        with:
          git-ref: ${{ env.SECP256K1_REF }}
          cache-version: ${{ env.SECP_CACHE_VERSION }}

      - name: Set up temp directory
        run: |
          echo 'TMPDIR=${{ runner.temp }}'  >> $GITHUB_ENV
          echo 'TMP=${{ runner.temp }}'     >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Cache cabal store
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cache-haddock-${{ runner.os }}-${{ matrix.ghc }}-v1-${{ hashFiles('cabal-cache.cabal') }}-${{ github.sha }}
          restore-keys: cache-haddock-${{ runner.os }}-${{ matrix.ghc }}-v1-${{ hashFiles('cabal-cache.cabal') }}-

      - name: Update Hackage index
        run: cabal update

      - name: Configure to use libsodium
        run: |
          cat >> ../../cabal.project <<EOF
          package cardano-crypto-praos
            flags: -external-libsodium-vrf
          EOF

      - name: build Haddock documentation 🔧
        run: |
          mkdir ./static/haddocks
          cd ../../
          cabal build --dry-run --enable-tests all
          ./scripts/docs/haddocks.sh

      - name: Build website
        run: yarn build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/website/build
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2

    # https://github.com/actions/deploy-pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
